### PR TITLE
add timer to quiz view (#293)

### LINKED ISSUE #293: licznik czasu na rozwiązanie quizu po stronie studenta
Widoczny w guziku i na popupie quizu. Działa jak po stronie prowadzącego.
Jakaś animacja jak jest końcówka czasu.

### PR DESCRIPTION
**Pull request by ostatni5**
Added timer.
Timer changes color if below 1:00 min
obraz

obraz

### CODE REVIEW

**Review by rozchlastywacz — CHANGES_REQUESTED** [review]
image

on the phone looks kinda weird...
tenor

**Comment by ostatni5** [comment]
Fixed on mobile.
obraz

**Review by rozchlastywacz — APPROVED** [review]

**Review by michal367 — APPROVED** [review]
obraz

**Pull request merged**
